export const dummyProducts = [
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg',
  },

  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/sample-image-url-for-testing-768x432.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/sample-image-url-for-testing-768x432.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/sample-image-url-for-testing-768x432.jpg',
  },

  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/sample-image-url-for-testing-768x432.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/sample-image-url-for-testing-768x432.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/sample-image-url-for-testing-768x432.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/sample-image-url-for-testing-768x432.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/sample-image-url-for-testing-768x432.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg',
  },
  {
    imageUrl:
      'https://www.pakainfo.com/wp-content/uploads/2021/09/sample-image-url-for-testing-768x432.jpg',
  },
]